### ISSUE TITLE
Download 

### ISSUE THREAD

**Issue by antokiller** [Prim69/ATEnchants#2]
Hey when i try to download that say error 404
https://github.com/Prim69/ATEnchants/archive/master.zip

**Comment by Prim69** [comment]
Click the download button directly from Github or if you want a phar heres the poggit link
https://poggit.pmmp.io/ci/Prim69/ATEnchants/~

**Comment by antokiller** [comment]
I try download on iphone they remove the download button

**Comment by Prim69** [comment]
Use the poggit link https://poggit.pmmp.io/ci/Prim69/ATEnchants/~ or 
https://github.com/Prim69/ATEnchants/archive/main.zip
